### PR TITLE
clean up redis/memcached after integration tests

### PR DESCRIPTION
**Pull request by aliyakamercan**
@DanSimon @nsauro

### CODE REVIEW

**Comment by DanSimon** [comment]
:+1:

**Comment by nsauro** [comment]
We don't want to do a flushall before/after each?

**Comment by nsauro** [comment]
I would at least make that list a Set if we are going to keep track, no need to wipe dupes(if they occur)

**Comment by aliyakamercan** [comment]
I don't think we want to flush all, cleaning up what is written is sufficient.

**Comment by nsauro** [comment]
Not fer nothin', but most of the delete commands accept multiple parameters.

**Pull request merged**
