### PR TITLE
Drop 2.10.6 Support

### PR DESCRIPTION
**Pull request by aliyakamercan**
- removed `crossScalaVersions`
- removed scala version and version check in travis.yml
- added new lines in travis.yml

#554 

@benblack86 @DanSimon @jlbelmonte @dxuhuang

### CODE REVIEW

**Comment by benblack86** [comment]
I fine dropping 2.10, but don't we also want to support 2.12? Or does 2.11 not work with the latest akka?

**Comment by aliyakamercan** [comment]
We need to update akka before that.

**Comment by aliyakamercan** [comment]
@benblack86 updated akka and added 2.12. 
#548 #372

**Comment by DanSimon** [comment]
LGTM 👍  

The last time I tried building colossus on 2.12 it was significantly (but not dramatically) slower in benchmarks.  I will be very interested to see how it does now.

**Pull request merged**
