### PR TITLE
adding server_error value to reply

### LINKED ISSUE #267: Memcached Client not correctly handling SERVER_ERROR
currently, if memcached returns SERVER_ERROR, we get the following stacktrace.  It should handle it gracefully:

colossus.parsing.ParseException: Unknown reply 'SERVER_ERROR'
        at colossus.protocols.memcache.MemcacheReplyParser$$anonfun$reply$1.apply(Memcache.scala:284)
        at colossus.protocols.memcache.MemcacheReplyParser$$anonfun$reply$1.apply(Memcache.scala:273)
        at colossus.parsing.Combinators$Parser$$anon$4$$anonfun$parse$4.apply(Parsing.scala:256)
        at colossus.parsing.Combinators$Parser$$anon$4$$anonfun$parse$4.apply(Parsing.scala:256)
        at scala.Option.map(Option.scala:146)

### PR DESCRIPTION
**Pull request by amotamed**
fixes #267 
Adding handling of SERVER_ERROR from memcached.  The value of the error is a human readable string that the server kicks back.  Please check out line 109 here: https://github.com/memcached/memcached/blob/master/doc/protocol.txt

### CODE REVIEW

**Comment by DanSimon** [comment]
Can you add a unit test with an example of such an error?  Also can you edit your description adding the text "fixes #267 ", which will cause github to auto-close the issue when this branch gets merged.

**Comment by nsauro** [comment]
How did you test this?

**Comment by aliyakamercan** [comment]
:+1:

**Comment by nsauro** [comment]
:+1:

**Comment by DanSimon** [comment]
Nice :+1:

**Pull request merged**
