### PR TITLE
Fix publish script for snapshots

### PR DESCRIPTION
**Pull request by aliyakamercan**
@amotamed @jlbelmonte @benblack86 @DanSimon @dxuhuang 

Checking `-SNAPSHOT` git tag. 

I am not sure about this. Maybe we should release snapshots with each merge to develop (<version>_<commit sha>-SNAPSHOT) ?

Any preferences?

### CODE REVIEW

**Comment by benblack86** [comment]
What is `TRAVIS_BRANCH`?

**Comment by aliyakamercan** [comment]
It is the tag in this case. For PRs there are 2 builds;  PR branch and the branch it is being merged to.

**Comment by DanSimon** [comment]
Personally I don't think think auto-publishing a snapshot with merges to develop is particularly useful, so I'm fine with dropping that.  Someone asked for it a long time ago and I don't know if anyone has actually used it.  

But that said, what's the reason for making this change?  I don't think we should be publishing very many snapshots anyway.  It's easy enough to build and publish Colossus locally if you want to test a change you just made.  And we should be publishing milestone/candidate releases often enough for any pre-release testing.

**Comment by aliyakamercan** [comment]
@dan Yes, I guess we can release milestones and releases candidates of off develop. Regardless
```bash
($TRAVIS_PULL_REQUEST == "false" && $TRAVIS_BRANCH == "develop" && $(cat version.sbt) =~ "-SNAPSHOT")
```
this piece of code is wrong since branch cannot be `develop` on a non-pr build. I will remove that bit altogether, we will only be able to make milestone, rc and regular releases.

**Comment by aliyakamercan** [comment]
@benblack86 @DanSimon please take a look again.

**Pull request merged**
