### PR TITLE
Add more redis commands

### PR DESCRIPTION
**Pull request by benblack86**
More redis commands. Not sure if any of these should be in the "commands we are ok with failing over to a slave" list.

### CODE REVIEW

**Comment by DanSimon** [comment]
Travis is failing because there's a bug in our travis config with how we handle our encrypted stuff.  I'll try to get a fix in asap.  Code looks good otherwise.

**Comment by DanSimon** [comment]
@benblack86 try merging master into your branch and re-running travis.  We just merged a fix to our travis config but I think that change has to be on your branch.

**Comment by benblack86** [comment]
Nearly...

**Comment by DanSimon** [comment]
:+1:

**Pull request merged**
