### PR TITLE
Update version of dependencies + improve efficiency of handling HTTP and Websocker protocols

### PR DESCRIPTION
**Pull request by plokhotnyuk**

### CODE REVIEW

**Comment by dkarivalis** [comment]
hey @plokhotnyuk! thank you for your contributions :) would you mind filling out the PR description with "what" / "testing" sections?

for the http/websocket optimizations, do you still have your benchmark results? i can assist if needed!

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by plokhotnyuk** [comment]
@yahoocla I have signed CLA. Here is response from https://yahoocla.herokuapp.com/ server, when I logging in with my GitHub account:
```
Good to see you, Andriy Plokhotnyuk

You previously signed this CLA on:
Fri Mar 29 2019 17:42:40 GMT+0000 (UTC)
From: 5.173.61.253 
```

**Comment by plokhotnyuk** [comment]
@dkarivalis The main idea of this PR was updating of dependencies and checking how long it will take to be released.

Also, during profiling of some examples at high load there were detected places for improvements (mostly in parsing of HTTP headers).

If you are still interested in such kind of improvements, please, let me know. I will refresh them and split on different PRs with more descriptions.

**Comment by dkarivalis** [comment]
@plokhotnyuk yes, we are definitely interested in your optimizations! i'll be able to review, test, & benchmark. please assign me on the refreshed PR's ^_^

also i will sync with our security team about sign-off on the dependency updates. thanks!

**Pull request closed without merging**
