### PR TITLE
#496 Make Websocket origin header optional

### PR DESCRIPTION
**Pull request by shmishleniy**
issue https://github.com/tumblr/colossus/issues/496

### CODE REVIEW

**Comment by DanSimon** [comment]
This looks good to me 👍 .  If you haven't already, we'll need you to submit a CLA as described in our [contributing guidelines](https://github.com/tumblr/colossus/blob/master/CONTRIBUTING.md) before I can merge this in.

**Comment by shmishleniy** [comment]
Some problem with legal@tumblr.com 

This is an automatically generated message.
cmm@yahoo-inc.com is no longer with Yahoo! Inc.
Your message will not be forwarded.

**Comment by DanSimon** [comment]
Hey @shmishleniy , apologies this is taking so long, I'm trying to get the situation resolved.

**Comment by DanSimon** [comment]
Ok it appears we did receive the CLA after all, so this is good to go

**Pull request merged**
