### PR TITLE
Remove trailing whitespace

### PR DESCRIPTION
**Pull request by jtescher**
There are a lot of files with trailing whitespace. This commit removes them from Scala files via:

```shell
$ find . -name '*.scala' -type f -print0 | xargs -0 sed -i '' -E "s/[[:space:]]*$//"
```

### CODE REVIEW

**Comment by DanSimon** [comment]
Looks fine to me.  

If you haven't already, you'll need to sign a CLA before I can merge these changes (a little silly since it's just whitespace changes but that's the rules), otherwise this looks good to go.

**Comment by DanSimon** [comment]
Oops, meant to include a link to the CLA, it's [here](http://static.tumblr.com/zyubucd/GaTngbrpr/tumblr_corporate_contributor_license_agreement_v1__10-7-14.pdf).  Also don't worry about the code coverage failure, it's not an issue since no actual code is changed here.

**Comment by jtescher** [comment]
Emailed.

**Comment by DanSimon** [comment]
Thanks.  It looks like there's a few conflicts that popped up after merging another PR.  As soon as those are fixed this will be good to merge.

**Comment by DanSimon** [comment]
FYI I fixed the conflicts myself and merged manually, so all is done here 👍

**Pull request merged**
